// KSL (Kaiseki Script Language) — syntax lexer.
//
// Produces (byte-range, TokenKind) pairs for one line of KSL source.
// No AST is built — KSL is a read-only notation generated by LLMs and
// consumed directly as text; the lexer exists only for syntax highlighting.
//
// Token classification:
//
//   TokenKind       Examples
//   ─────────────   ────────────────────────────────────────────────────────
//   Keyword         fn  struct  virtual  interface  let  var  throws  as  mut
//   Atom            null  default  true  false  self
//   Ident           BEE_Layer  get_stream_fpv  local_90
//   Number          42  0x290  0xe2b340
//   Offset          @0x0290   (entire annotation including the @ sigil)
//   DocComment      /// doc text
//   SectionSep      // ── Title ──────────────────────────────────────────
//   Comment         // regular comment
//   Operator        !  ->  ??  &&  ||  ==  !=  *  &  ...
//   Punct           {  }  (  )  ,  :  ?
//   Whitespace      spaces and tabs
//   Unknown         non-ASCII characters or unrecognized bytes

use std::ops::Range;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TokenKind {
	Keyword,
	Atom,
	Ident,
	Number,
	// @0xNNNN — the entire annotation token, including the @ sigil.
	Offset,
	DocComment,
	// // ── Title ──────  (detected by presence of U+2500 BOX DRAWINGS LIGHT HORIZONTAL ─)
	SectionSep,
	Comment,
	Operator,
	Punct,
	Whitespace,
	Unknown,
}

pub struct Token {
	pub kind: TokenKind,
	pub range: Range<usize>,
}

// ── Keyword tables ────────────────────────────────────────────────────────────

const KEYWORDS: &[&str] = &[
	"fn",
	"struct",
	"virtual",
	"interface",
	"type",
	"let",
	"var",
	"if",
	"else",
	"return",
	"throws",
	"as",
	"mut",
];

// Distinguished from identifiers so they can share color with numeric literals.
const ATOMS: &[&str] = &["null", "default", "true", "false", "self"];

// ── Tokenizer ─────────────────────────────────────────────────────────────────

/// Tokenize one line of KSL source (without a trailing newline).
/// Returns a flat list of non-overlapping tokens in source order.
pub fn tokenize(line: &str) -> Vec<Token> {
	let src = line.as_bytes();
	let len = src.len();
	let mut tokens: Vec<Token> = Vec::new();
	let mut i = 0usize;

	while i < len {
		let start = i;

		// ── Whitespace ────────────────────────────────────────────────────────
		if src[i] == b' ' || src[i] == b'\t' {
			while i < len && (src[i] == b' ' || src[i] == b'\t') {
				i += 1;
			}
			tokens.push(Token {
				kind: TokenKind::Whitespace,
				range: start..i,
			});
			continue;
		}

		// ── Comment — consumes the entire remainder of the line ───────────────
		// KSL has no block comments; // always runs to end-of-line.
		if src[i] == b'/' && i + 1 < len && src[i + 1] == b'/' {
			i = len;
			let text = &line[start..];
			let kind = if text.starts_with("///") {
				TokenKind::DocComment
			} else if text.contains('\u{2500}') {
				// Section separators contain U+2500 BOX DRAWINGS LIGHT HORIZONTAL (─)
				TokenKind::SectionSep
			} else {
				TokenKind::Comment
			};
			tokens.push(Token { kind, range: start..i });
			continue;
		}

		// ── Offset annotation: @0xNNNN ────────────────────────────────────────
		if src[i] == b'@' {
			i += 1;
			if i + 1 < len && src[i] == b'0' && src[i + 1] == b'x' {
				i += 2;
				while i < len && src[i].is_ascii_hexdigit() {
					i += 1;
				}
			}
			tokens.push(Token {
				kind: TokenKind::Offset,
				range: start..i,
			});
			continue;
		}

		// ── Hex literal: 0xNNNN ───────────────────────────────────────────────
		if src[i] == b'0' && i + 1 < len && src[i + 1] == b'x' {
			i += 2;
			while i < len && src[i].is_ascii_hexdigit() {
				i += 1;
			}
			tokens.push(Token {
				kind: TokenKind::Number,
				range: start..i,
			});
			continue;
		}

		// ── Decimal integer ───────────────────────────────────────────────────
		if src[i].is_ascii_digit() {
			while i < len && src[i].is_ascii_digit() {
				i += 1;
			}
			tokens.push(Token {
				kind: TokenKind::Number,
				range: start..i,
			});
			continue;
		}

		// ── Identifier, keyword, or atom ──────────────────────────────────────
		if src[i].is_ascii_alphabetic() || src[i] == b'_' {
			while i < len && (src[i].is_ascii_alphanumeric() || src[i] == b'_') {
				i += 1;
			}
			let word = &line[start..i];
			let kind = if KEYWORDS.contains(&word) {
				TokenKind::Keyword
			} else if ATOMS.contains(&word) {
				TokenKind::Atom
			} else {
				TokenKind::Ident
			};
			tokens.push(Token { kind, range: start..i });
			continue;
		}

		// ── Multi-character operators — longest-match ─────────────────────────
		let remaining = len - i;

		if remaining >= 3 && src[i..i + 3] == *b"..." {
			i += 3;
			tokens.push(Token {
				kind: TokenKind::Operator,
				range: start..i,
			});
			continue;
		}

		if remaining >= 2 {
			let pair = &src[i..i + 2];
			if matches!(
				pair,
				b"->" | b"??" | b"<<" | b">>" | b"&&" | b"||" | b"!=" | b"==" | b"<=" | b">="
			) {
				i += 2;
				tokens.push(Token {
					kind: TokenKind::Operator,
					range: start..i,
				});
				continue;
			}
		}

		// ── Single-character operators ────────────────────────────────────────
		if matches!(
			src[i],
			b'!' | b'*' | b'&' | b'|' | b'^' | b'+' | b'-' | b'%' | b'<' | b'>' | b'='
		) {
			i += 1;
			tokens.push(Token {
				kind: TokenKind::Operator,
				range: start..i,
			});
			continue;
		}

		// ── Punctuation ───────────────────────────────────────────────────────
		if matches!(
			src[i],
			b'{' | b'}' | b'(' | b')' | b'[' | b']' | b',' | b':' | b';' | b'.' | b'?'
		) {
			i += 1;
			tokens.push(Token {
				kind: TokenKind::Punct,
				range: start..i,
			});
			continue;
		}

		// ── Non-ASCII UTF-8 or unrecognized byte ──────────────────────────────
		// Advance by the full UTF-8 character width to avoid splitting a sequence.
		let char_width = match src[i] {
			0x00..=0x7F => 1,
			0xC0..=0xDF => 2,
			0xE0..=0xEF => 3,
			_ => 4,
		};
		i += char_width.min(remaining);
		tokens.push(Token {
			kind: TokenKind::Unknown,
			range: start..i,
		});
	}

	tokens
}
